language: node_js
node_js:
- 10.15.0
branches:
  only:
  - master

install: npm install

notifications:
  email:
    recipients:
      - sherlockblaze@gmail.com
    on_success: change
    on_failure: always

before_script:
- git config --global user.name "sherlockblaze"
- git config --global user.email "sherlockblaze@gmail.com"

script:
  npm run build

after_script:
- sed -i "s/__VISITORS_APPID__/${__VALINE_APPID__}/" _config.yml
- sed -i "s/__VISITORS_APPKEY__/${__VALINE_APPKEY__}/" _config.yml
- sed -i "s|__GIT_KIND__|github|" _config.yml
- sed -i "s|__GIT_REPO__|${__GITHUB_REPO__}|" _config.yml
- hexo deploy