language: node_js
node_js:
- 10.15.0
branches:
  only:
  - master

install: npm install

notifications:
  email:
    recipients:
      - sherlockblaze@gmail.com
    on_success: change
    on_failure: always

before_script:
- git config --global user.name "sherlockblaze"
- git config --global user.email "sherlockblaze@gmail.com"
- sed -i "s/__VISITORS_APPID__/${__VISITORS_APPID__}/" _config.yml
- sed -i "s/__VISITORS_APPKEY__/${__VISITORS_APPKEY__}/" _config.yml

script:
  npm run build

after_script:
- mkdir temp
- mv public/2017/ temp/
- mv public/2018/ temp/
- mv public/2019/ temp/
- mv public/2020/ temp/
- rm -rf source/_posts/*
- npm run build
- rm public/resources/blog/index.txt
- mv temp/2017 public/resources/blog
- mv temp/2018 public/resources/blog
- mv temp/2019 public/resources/blog
- mv temp/2020 public/resources/blog
- rm -rf temp
- sed -i "s|__GIT_KIND__|github|" _config.yml
- sed -i "s|__GIT_REPO__|${__GITHUB_REPO__}|" _config.yml
- hexo deploy
